### PR TITLE
[WIP] Add tests to improve coverage

### PR DESCRIPTION
**Pull request by lwr20**
Please do not merge for now.  This is used for CI runs.

### CODE REVIEW

**Comment by lwr20** [comment]
retest this please

**Comment by tomdee** [comment]
@lwr20 What's happening with this PR?

**Comment by lwr20** [comment]
Not much at present.  The intent was to automate away much of QA, but we're not likely to get round to that for a while.

**Comment by lwr20** [comment]
Closing for now.

**Pull request closed without merging**
