### PR TITLE
[Don't merge] use upstream confd

### PR DESCRIPTION
**Pull request by gunjan5**

### CODE REVIEW

**Comment by caseydavenport** [comment]
This isn't going into v1.0.0, but we should look at this shortly after.

**Comment by tomdee** [comment]
@gunjan5 Can you remind me why this didn't work?

**Comment by tomdee** [comment]
@gunjan5 I thought we were going to try https://github.com/bacongobbler/confd/releases/tag/v0.12.1

**Comment by gunjan5** [comment]
Closing this in favor of #1488

**Pull request closed without merging**
