### PR TITLE
ST GoBGP backend

### PR DESCRIPTION
**Pull request by ishidawataru**
Signed-off-by: Wataru Ishida <ishida.wataru@lab.ntt.co.jp>

### CODE REVIEW

**Comment by ishidawataru** [comment]
respin of https://github.com/projectcalico/calicoctl/pull/1382 (closed mistakenly)

projectcalico/calico-bgp-daemon#20 is needed to be merged to pass ST.

**Comment by gunjan5** [comment]
this PR needs to be rebased once https://github.com/projectcalico/calicoctl/pull/1574 is merged

**Comment by tomdee** [comment]
Please just merge #1574 into this PR so we can see the tests passing...

**Comment by robbrockbank** [comment]
@ishidawataru Hi, we just released a new GoBGP daemon and revved our calico/node container to use that image.

Would it be possible to rebase so that you are picking up the latest changes - hopefully the tests will then pass.

**Comment by ishidawataru** [comment]
@robbrockbank Rebased and all tests passed :)

**Comment by gunjan5** [comment]
LGTM

**Comment by robbrockbank** [comment]
LGTM

@ishidawataru I'm tempted to merge this as is  since it all looks great!  I _think_ there are a couple of missing tests though:
-  Testing /26 handling.  There is a TODO in TestBGPBackends() which should be removed and add "--ip=XXXX" options to each host to select IPs within the same /26.
-  Testing IPIP mode of cross-subnet.  The test for this is (perhaps confusingly), in calicoctl (test_ipip).  I think we probably just want to do this for both backends.

**Comment by ishidawataru** [comment]
@robbrockbank I'll work on testing /26 handling within this PR.
I'd like to make testing IPIP as a separate PR since it needs more work.
Currently `allocate-ipip-addr` is not called when gobgp backend is used. (this prevents `test_ipip` to pass for gobgp backend)

I think we need to make [this](https://github.com/projectcalico/calicoctl/blob/master/calico_node/allocateipip/allocate_ipip_addr.go) as a library and call below inside gobgp backend.

```go
if cidrs := getIPIPEnabledPoolCIDRs(c); len(cidrs) > 0 {
		ensureHostTunnelAddress(c, nodename, cidrs)
	} else {
		removeHostTunnelAddr(c, nodename)
}
```

**Comment by ishidawataru** [comment]
Updated to test /26 handling. @robbrockbank PTAL

@robbrockbank @gunjan5 I come to think that it would be better to move `allocate-ipip-addr` function inside `felix`?
Felix is already managing the IPIP device, so it is natural to let him also manage IP address of it. 
WDYT?

**Comment by robbrockbank** [comment]
This LGTM, so merging.

I've raised #1581 to cover adding IPIP tests for GoBGP.  Regarding the moving of the tunnel address processing to Felix - I'm less certain about that - we haven't yet had Felix involved in IPAM - it's an interesting thought though - let me think about this and I'll get back to you.

**Pull request merged**
