### PR TITLE
Use calico/node image from quay.io

### PR DESCRIPTION
**Pull request by caseydavenport**
See related https://github.com/projectcalico/calico/pull/419

### CODE REVIEW

**Comment by gunjan5** [comment]
We should also update the cloud-config for the demos which caches dockerhub image right now https://github.com/projectcalico/calico/blob/master/master/getting-started/docker/installation/vagrant-ubuntu/Vagrantfile#L56 . I don't see that in your other PR https://github.com/projectcalico/calico/pull/419 . Once there's a PR/issue/update in PR 419 for it, this LGTM

**Comment by robbrockbank** [comment]
Could you check one thing out...  Last couple of times I pushed to quay.io the image got stuck for hours (literally) in an image validation check during which time I couldn't seem to pull the image.

Could you check whether this was user error on my part or not.   It could be problematic doing a release if it takes hours for the pushed image to be pullable again.  I think this must have been user error, but I think it's worthy of a quick test.

**Comment by caseydavenport** [comment]
@gunjan5 Updated 419 to fix those missing images.

@robbrockbank I seem to be able to push and pull tags immediately. 

Any idea what's going on with Semaphore?

```
docker: Error response from daemon: Error processing tar file(exit status 1): write /usr/lib/python2.7/lib-dynload/_ctypes_test.so: no space left on device.
```

**Comment by gunjan5** [comment]
@caseydavenport not sure how those errors are related to this change. I just kicked off another build to see if it was a transient thing, but doesn't seem like it. 
Maybe rebase your changes to see if it works now since the tests have changed since this PR?

**Pull request merged**
