### PR TITLE
Updated calicoctl RHEL UBI image to 8.5

### PR DESCRIPTION
**Pull request by Akasurde**
## Description
Update RHEL UBI image from 8.2 to 8.5.

Fixes: #2460 

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by Akasurde** [comment]
cc @caseydavenport

**Review by caseydavenport — APPROVED** [review]

**Comment by caseydavenport** [comment]
@Akasurde thanks for fixing this!

**Comment by Akasurde** [comment]
@caseydavenport Thanks for the review and merge.

**Pull request merged**
