### PR TITLE
Move calico/node elsewhere

### PR DESCRIPTION
**Pull request by tomdee**

### CODE REVIEW

**Comment by robbrockbank** [comment]
Conflicts need resolving.

These changes themselves look fine to me, but we now have no automated testing of this repo.

**Comment by tomdee** [comment]
There is still automated testing - the calicoctl UTs are still in this repo.

**Comment by robbrockbank** [comment]
The UTs are rather lacking in calicoctl - most of the testing was handled in our ST framework.

Even with beefed up UTs though, this repo still needs some e2e testing of the actual calicoctl binary.  Perhaps running through a subset of the STs would be easiest (and we may also want to do that for the confd/bird repos too).

**Comment by robbrockbank** [comment]
Otherwise LGTM.

**Comment by robbrockbank** [comment]
The RELEASING.md doc needs updating.

**Comment by robbrockbank** [comment]
lgtm

**Pull request merged**
